import { jambiereURL, epauliereURL, nikeURL, plastronURL, casqueURL, bouclierURL } from "../../graphisme/item/item";
import kippa from '../../asset/item/armure/kippa.png';

export const lexiqueArmure = {
    
    plastron: {
        id: 'plastron',
        nom: 'plastron',
        img: plastronURL,
        description: 'plastron',
        valeur: 5,
        action: 5,
        poid: 28,
        important: 'non',
        type: 'armure',
        cible: 'buste',
    },
    bouclier: {
        id: 'bouclier',
        nom: 'bouclier',
        img: bouclierURL,
        description: 'bouclier',
        valeur: 30,
        action: 5,
        poid: 17,
        important: 'non',
        type: 'armure',
        cible: 'main',
    },
    jambiere: {
        id: 'jambiere',
        nom: 'jambiere',
        img: jambiereURL,
        description: 'jambiere',
        valeur: 30,
        action: 5,
        poid: 11,
        important: 'non',
        type: 'armure',
        cible: 'jambe',
    },
    epauliere: {
        id: 'epauliere',
        nom: 'epauliere',
        img: epauliereURL,
        description: 'epauliere',
        valeur: 30,
        action: 5,
        poid: 8,
        important: 'non',
        type: 'armure',
        cible: 'epaule',
    },
    nike: {
        id: 'nike',
        nom: 'nike',
        img: nikeURL,
        description: 'nike',
        valeur: 30,
        action: 5,
        poid: 6,
        important: 'non',
        type: 'armure',
        cible: 'pied',
    },
    casque: {
        id: 'casque',
        nom: 'casque',
        img: casqueURL,
        description: 'casque',
        valeur: 30,
        action: 5,
        poid: 13,
        important: 'non',
        type: 'armure',
        cible: 'tete',
    },
    kippa: {
        id: 'kippa',
        nom: 'Kippa',
        img: kippa,
        description: "Une kippa qui favorise votre CHANCE, elle permet d'obtenir des réductions",
        valeur: 563,
        action: 1,
        poid: 1,
        important: 'non',
        type: 'armure',
        cible: 'tete',
    },
}